name: Build
description: 'Install Win32 specific dependencies'

inputs:
  shell:
    required: false
    default: bash

runs:
  using: 'composite'
  steps:
    - name: Fix location of lrelease executable
      shell: ${{inputs.shell}}
      run: ln -s `which lrelease-qt6` /mingw64/bin/lrelease.exe

      
