name: Build
description: 'Install Win32 specific dependencies'

inputs:
  shell:
    required: false
    default: msys2 {0}

runs:
  using: 'composite'
  steps:
    - name: Install MSys2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        path-type: inherit
        release: true
        update: true
        install: base-devel mingw-w64-x86_64-toolchain


    - name: Install dependencies explicitly
      shell: ${{inputs.shell}}
      run: pacman -Suyy git mingw-w64-x86_64-cc mingw-w64-x86_64-make mingw-w64-x86_64-cmake mingw-w64-x86_64-libsndfile mingw-w64-x86_64-fftw mingw-w64-x86_64-volk mingw-w64-x86_64-libxml2 mingw-w64-x86_64-libusb mingw-w64-x86_64-qt6 mingw-w64-x86_64-portaudio zip mingw-w64-x86_64-soapysdr mingw-w64-x86_64-sopayrhackrf mingw-w64-x86_64-soapyrtlsdr
          
    - name: Listing everything on /mingw64 to ease debugging
      shell: ${{inputs.shell}}
      run: ls /mingw64/bin
      
    - name: List the whole root and see where the heck this joke of OS installed Qt6
      shell: ${{inputs.shell}}
      run: ls -lR /
      
    - name: Fix location of lrelease executable
      shell: ${{inputs.shell}}
      run: ln -s /mingw64/bin/lrelease-qt6.exe /mingw64/bin/lrelease.exe

      
